// Created by Ben Roberts

#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/f187a26c-defb-4d92-970c-4c3da18ff192

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int brightness;
  bool win;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

int led = 6;         // the PWM pin the LED is attached to
int correctNum = 0;

void setupGame() {  // Reset the game
  correctNum = random(10);
  brightness = 0;
  submit = false;
  win = false;
}

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);

  pinMode(led, OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(4);
  ArduinoCloud.printDebugInfo();

  randomSeed(analogRead(5));
  setupGame();
}

void loop() {
  ArduinoCloud.update();
}


void onBrightnessChange()  {
  analogWrite(led, map(abs(correctNum - brightness), 0, 10, 255, 0));
}

void onWinChange()  {
  setupGame();  // Ideal case
}

void onSubmitChange() {
    if (submit == true) {
      if (correctNum == brightness) {
        win = true;
        Serial.println("You Win!");
    }
    else {
      win = false;
      Serial.println("You Lose!");
      setupGame();
    }
  }
}