// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBrightnessChange();
void onSubmitChange();
void onWinChange();

int brightness;
bool submit;
bool win;

void initProperties(){

  ArduinoCloud.addProperty(brightness, READWRITE, ON_CHANGE, onBrightnessChange);
  ArduinoCloud.addProperty(submit, READWRITE, ON_CHANGE, onSubmitChange);
  ArduinoCloud.addProperty(win, READWRITE, ON_CHANGE, onWinChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
